name: CF00.06 Compliance Validation
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM

jobs:
  cf0006-compliance:
    runs-on: ubuntu-latest
    name: CF00.06 Compliance Check
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install CF00.06 validation tools
      run: |
        pip install PyYAML requests matplotlib seaborn pandas
        
    - name: Download CF00.06 validator
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"              -H "Accept: application/vnd.github.v3.raw"              -o cf0006_validator.py              https://api.github.com/repos/quantxtrader/quantx-tools/contents/02_OPERATIONS/04_SUPPORT/cf00.06-validation/cf0006_validator_v1.0.py
        
    - name: Run CF00.06 compliance validation
      run: |
        python cf0006_validator.py . --output-format markdown
        
    - name: Upload compliance report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cf0006-compliance-report
        path: compliance_report.md
        
    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          if (fs.existsSync('compliance_report.md')) {
            const report = fs.readFileSync('compliance_report.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## CF00.06 Compliance Report\n\n' + report
            });
          }
